const String supabaseUrl = 'https://jfkvsducukwgqsljoisw.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impma3ZzZHVjdWt3Z3FzbGpvaXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxODI5NTgsImV4cCI6MjA4MDc1ODk1OH0.twdtSeDGoMCsaqAgDh5kwlzIkKlL78fUNIdErYE9wr8';
